In [2]:
%matplotlib inline

# Torch tensors

In [5]:
import torch
import math

In [ ]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[ 2.8026e-45,  8.4078e-45,  2.8026e-45,  1.8217e-44],
        [ 3.3631e-44,  4.4521e-41,  1.3902e-38,  0.0000e+00],
        [ 1.4013e-45,  4.4521e-41, -3.3642e-01,  4.4521e-41]])


In [ ]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [ ]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [ ]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[3.2397e-34, 0.0000e+00, 2.1624e-01],
         [9.9269e-01, 8.9683e-44, 0.0000e+00]],

        [[1.1210e-43, 0.0000e+00, 4.5006e-41],
         [0.0000e+00,        nan,        nan]]])
torch.Size([2, 2, 3])
tensor([[[-3.8140e-10,  4.4522e-41, -3.8140e-10],
         [ 4.4522e-41,  4.4842e-44,  0.0000e+00]],

        [[ 1.1210e-43,  0.0000e+00,  1.8732e-34],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [ ]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [ ]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


In [ ]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [ ]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


In [ ]:
a = torch.rand(2, 3)
b = torch.rand(3, 2)

print(a * b)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
# tensor broadcasting

rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.2138, 0.5395, 0.3686, 0.4007],
        [0.7220, 0.8217, 0.2612, 0.7375]])
tensor([[0.4276, 1.0791, 0.7371, 0.8014],
        [1.4439, 1.6434, 0.5224, 1.4750]])


In [ ]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.8328, 0.8444],
         [0.2941, 0.3788],
         [0.4567, 0.0649]],

        [[0.8328, 0.8444],
         [0.2941, 0.3788],
         [0.4567, 0.0649]],

        [[0.8328, 0.8444],
         [0.2941, 0.3788],
         [0.4567, 0.0649]],

        [[0.8328, 0.8444],
         [0.2941, 0.3788],
         [0.4567, 0.0649]]])
tensor([[[0.6677, 0.6677],
         [0.7826, 0.7826],
         [0.1332, 0.1332]],

        [[0.6677, 0.6677],
         [0.7826, 0.7826],
         [0.1332, 0.1332]],

        [[0.6677, 0.6677],
         [0.7826, 0.7826],
         [0.1332, 0.1332]],

        [[0.6677, 0.6677],
         [0.7826, 0.7826],
         [0.1332, 0.1332]]])
tensor([[[0.0023, 0.4945],
         [0.0023, 0.4945],
         [0.0023, 0.4945]],

        [[0.0023, 0.4945],
         [0.0023, 0.4945],
         [0.0023, 0.4945]],

        [[0.0023, 0.4945],
         [0.0023, 0.4945],
         [0.0023, 0.4945]],

        [[0.0023, 0.4945],
         [0.0023, 0.4945],
         [0.0023, 0.4945]]])


In [ ]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(4, 3)    # dimensions must match last-to-first


c = a * torch.rand(   2, 3) # both 3rd & 2nd dims different


d = a * torch.rand((0, ))   # can't broadcast with an empty tensor

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [ ]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.linalg.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.linalg.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.linalg.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.3846, 0.5091, 0.5491, 0.5340],
        [0.6881, 0.8008, 0.2010, 0.2648]])
tensor([[1., 1., 1., -0.],
        [1., 1., -0., 1.]])
tensor([[ 0.,  0.,  0., -1.],
        [ 0.,  0., -1.,  0.]])
tensor([[ 0.3846,  0.5000,  0.5000, -0.5000],
        [ 0.5000,  0.5000, -0.2010,  0.2648]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.9464, 0.0113],
        [0.5183, 0.9807]])
tensor([[2.8392, 0.0340],
        [1.5548, 2.9421]])
torch.return_types.linalg_svd(
U=tensor([[-0.5847, -0.8113],
        [-0.8113,  0.5847]]),
S=tensor([3.7850, 2.1929]),
Vh=tensor([[-0.7718, -0.6359],
        [-0.6359,  0.7718]])

In [ ]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [ ]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.6545, 0.4144],
        [0.0696, 0.4648]])

After adding:
tensor([[1.6545, 1.4144],
        [1.0696, 1.4648]])
tensor([[1.6545, 1.4144],
        [1.0696, 1.4648]])
tensor([[0.6545, 0.4144],
        [0.0696, 0.4648]])

After multiplying
tensor([[0.4284, 0.1717],
        [0.0048, 0.2160]])
tensor([[0.4284, 0.1717],
        [0.0048, 0.2160]])


In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c) == old_id  # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.4365, 0.3659],
        [0.6642, 0.6050]])
tensor([[0.3285, 0.5655],
        [0.0065, 0.7765]])


In [ ]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


In [ ]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.3534, 0.7016],
        [0.6826, 0.9413]], requires_grad=True)
tensor([[0.3534, 0.7016],
        [0.6826, 0.9413]], grad_fn=<CloneBackward0>)
tensor([[0.3534, 0.7016],
        [0.6826, 0.9413]])
tensor([[0.3534, 0.7016],
        [0.6826, 0.9413]], requires_grad=True)


In [ ]:
!pip install pytorch-lightning

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.3/819.3 kB 20.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 927.3/927.3 kB 50.0 MB/s eta 0:00:00


In [ ]:
if torch.accelerator.is_available():
    gpu_rand = torch.rand(2, 2, device=torch.accelerator.current_accelerator())
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

AttributeError: module 'torch' has no attribute 'accelerator'

In [ ]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

AttributeError: module 'torch' has no attribute 'accelerator'

In [ ]:
y = torch.rand(2, 2)
y = y.to(my_device)

NameError: name 'my_device' is not defined

In [ ]:
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='cuda')
z = x + y  # exception will be thrown

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [ ]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [ ]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.0438]]]]])


In [ ]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.0636, 0.2884, 0.4362, 0.2368, 0.1394, 0.1721, 0.1751, 0.3851, 0.0732,
         0.3118, 0.9180, 0.7293, 0.5351, 0.5078, 0.8012, 0.5088, 0.3142, 0.8068,
         0.6503, 0.4621]])
torch.Size([20])
tensor([0.0636, 0.2884, 0.4362, 0.2368, 0.1394, 0.1721, 0.1751, 0.3851, 0.0732,
        0.3118, 0.9180, 0.7293, 0.5351, 0.5078, 0.8012, 0.5088, 0.3142, 0.8068,
        0.6503, 0.4621])
torch.Size([2, 2])
torch.Size([2, 2])


In [ ]:
a = torch.ones(4, 3, 2)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.1451, 0.1451],
         [0.7946, 0.7946],
         [0.4126, 0.4126]],

        [[0.1451, 0.1451],
         [0.7946, 0.7946],
         [0.4126, 0.4126]],

        [[0.1451, 0.1451],
         [0.7946, 0.7946],
         [0.4126, 0.4126]],

        [[0.1451, 0.1451],
         [0.7946, 0.7946],
         [0.4126, 0.4126]]])


In [ ]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

torch.Size([3, 1])
tensor([[[0.1625, 0.1625],
         [0.9214, 0.9214],
         [0.2327, 0.2327]],

        [[0.1625, 0.1625],
         [0.9214, 0.9214],
         [0.2327, 0.2327]],

        [[0.1625, 0.1625],
         [0.9214, 0.9214],
         [0.2327, 0.2327]],

        [[0.1625, 0.1625],
         [0.9214, 0.9214],
         [0.2327, 0.2327]]])


In [ ]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


In [ ]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


In [ ]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.5506, 0.3014, 0.0750],
        [0.2174, 0.3361, 0.0722]])
[[0.55057985 0.3013537  0.0750469 ]
 [0.21738154 0.33607328 0.07215607]]


In [ ]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.55057985  0.3013537   0.0750469 ]
 [ 0.21738154 17.          0.07215607]]
